import React from 'react';
import Head from 'next/head';
import {
  CartSection,
  ExtraMenuSection,
  Footer,
  Gap,
  MenuSection,
  Navbar,
} from '../../components';

const MyCart = () => {
  return (
    <div>
      <Head>
        <title>Grill and Chill</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className="h-screen">
        <CartSection />
        <ExtraMenuSection />
        <MenuSection />
        <Gap height="65px" width="150px" />
        <Footer />
      </main>
    </div>
  );
};

export default MyCart;
