import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import {
  AboutUsSection,
  HeroSection,
  MenuSection,
  Navbar,
} from '../components';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Grill and Chill</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className="h-screen">
        <HeroSection />
        <MenuSection />
        <AboutUsSection />
      </main>
    </div>
  );
};

export default Home;
