import React from 'react';
import Head from 'next/head';
import { Footer, Navbar, SuccessSection } from '../../components';

const Success = () => {
  return (
    <div>
      <Head>
        <title>Grill and Chill</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className="h-screen">
        <SuccessSection />
        <Footer />
      </main>
    </div>
  );
};

export default Success;
